modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="m1917gun"
version="1.0.0"
displayName="M1917Gun"
credits="Nope"
authors="Pluto mingwang"
description='''
在游戏内添加了m1917美国制史密斯维森
'''

[[dependencies.m1917gun]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




